window.workbenchData = {
  "summary": {
    "roles": 42,
    "pipeline_events": 1646,
    "weekly_rows": 336,
    "critical_roles": 31,
    "avg_readiness": 36.4,
    "avg_fill_risk": 70.3,
    "quality_failures": 30,
    "top_role": {
      "role_id": "REQ018",
      "client_segment": "Industrial manufacturer",
      "role_family": "BI Analyst",
      "city": "Cincinnati",
      "work_structure": "Onsite",
      "priority": "Critical",
      "open_days": 75,
      "submit_rate": 42.9,
      "interview_rate": 22.2,
      "offer_rate": 0.0,
      "placement_readiness_score": 34.8,
      "fill_risk_score": 89.6,
      "data_quality_score": 55.8,
      "expected_shortlist_days": 18,
      "placements": 0,
      "estimated_weekly_margin": 810.0,
      "recommendation": "Clean source data before promising a new shortlist",
      "recruiter_owner": "Enterprise desk",
      "priority_score": 110.0
    }
  },
  "priorityQueue": [
    {
      "role_id": "REQ018",
      "client_segment": "Industrial manufacturer",
      "role_family": "BI Analyst",
      "city": "Cincinnati",
      "work_structure": "Onsite",
      "priority": "Critical",
      "open_days": 75,
      "submit_rate": 42.9,
      "interview_rate": 22.2,
      "offer_rate": 0.0,
      "placement_readiness_score": 34.8,
      "fill_risk_score": 89.6,
      "data_quality_score": 55.8,
      "expected_shortlist_days": 18,
      "placements": 0,
      "estimated_weekly_margin": 810.0,
      "recommendation": "Clean source data before promising a new shortlist",
      "recruiter_owner": "Enterprise desk",
      "priority_score": 110.0
    },
    {
      "role_id": "REQ006",
      "client_segment": "Hospitality group",
      "role_family": "Finance Analyst",
      "city": "Cincinnati",
      "work_structure": "Onsite",
      "priority": "Critical",
      "open_days": 65,
      "submit_rate": 42.3,
      "interview_rate": 36.7,
      "offer_rate": 9.1,
      "placement_readiness_score": 41.6,
      "fill_risk_score": 86.3,
      "data_quality_score": 61.0,
      "expected_shortlist_days": 16.5,
      "placements": 0,
      "estimated_weekly_margin": 840.0,
      "recommendation": "Clean source data before promising a new shortlist",
      "recruiter_owner": "Central desk",
      "priority_score": 103.4
    },
    {
      "role_id": "REQ032",
      "client_segment": "Regional bank",
      "role_family": "Data Engineer",
      "city": "Dayton",
      "work_structure": "Onsite",
      "priority": "Standard",
      "open_days": 68,
      "submit_rate": 33.3,
      "interview_rate": 0.0,
      "offer_rate": 0.0,
      "placement_readiness_score": 19.1,
      "fill_risk_score": 94.1,
      "data_quality_score": 26.8,
      "expected_shortlist_days": 18,
      "placements": 0,
      "estimated_weekly_margin": 232.0,
      "recommendation": "Clean source data before promising a new shortlist",
      "recruiter_owner": "Central desk",
      "priority_score": 92.1
    },
    {
      "role_id": "REQ001",
      "client_segment": "Healthcare network",
      "role_family": "BI Analyst",
      "city": "Columbus",
      "work_structure": "Onsite",
      "priority": "Critical",
      "open_days": 55,
      "submit_rate": 33.3,
      "interview_rate": 12.5,
      "offer_rate": 0.0,
      "placement_readiness_score": 28.0,
      "fill_risk_score": 82.9,
      "data_quality_score": 58.4,
      "expected_shortlist_days": 14.1,
      "placements": 0,
      "estimated_weekly_margin": 552.0,
      "recommendation": "Clean source data before promising a new shortlist",
      "recruiter_owner": "North desk",
      "priority_score": 91.9
    },
    {
      "role_id": "REQ009",
      "client_segment": "Healthcare network",
      "role_family": "Cybersecurity Analyst",
      "city": "Cleveland",
      "work_structure": "Hybrid",
      "priority": "Critical",
      "open_days": 51,
      "submit_rate": 42.3,
      "interview_rate": 31.8,
      "offer_rate": 0.0,
      "placement_readiness_score": 29.7,
      "fill_risk_score": 81.0,
      "data_quality_score": 21.4,
      "expected_shortlist_days": 16.1,
      "placements": 0,
      "estimated_weekly_margin": 660.0,
      "recommendation": "Clean source data before promising a new shortlist",
      "recruiter_owner": "Central desk",
      "priority_score": 90.1
    },
    {
      "role_id": "REQ021",
      "client_segment": "Energy utility",
      "role_family": "Cybersecurity Analyst",
      "city": "Cleveland",
      "work_structure": "Onsite",
      "priority": "High",
      "open_days": 57,
      "submit_rate": 33.3,
      "interview_rate": 11.1,
      "offer_rate": 0.0,
      "placement_readiness_score": 28.6,
      "fill_risk_score": 88.9,
      "data_quality_score": 58.4,
      "expected_shortlist_days": 16.2,
      "placements": 0,
      "estimated_weekly_margin": 252.0,
      "recommendation": "Clean source data before promising a new shortlist",
      "recruiter_owner": "Central desk",
      "priority_score": 88.1
    },
    {
      "role_id": "REQ038",
      "client_segment": "Hospitality group",
      "role_family": "Data Analyst",
      "city": "Dayton",
      "work_structure": "Hybrid",
      "priority": "High",
      "open_days": 49,
      "submit_rate": 34.5,
      "interview_rate": 27.6,
      "offer_rate": 0.0,
      "placement_readiness_score": 37.4,
      "fill_risk_score": 79.7,
      "data_quality_score": 79.2,
      "expected_shortlist_days": 15.4,
      "placements": 0,
      "estimated_weekly_margin": 986.0,
      "recommendation": "Escalate aging role in the client review",
      "recruiter_owner": "Enterprise desk",
      "priority_score": 87.0
    },
    {
      "role_id": "REQ042",
      "client_segment": "Industrial manufacturer",
      "role_family": "Cybersecurity Analyst",
      "city": "Cincinnati",
      "work_structure": "Onsite",
      "priority": "Standard",
      "open_days": 72,
      "submit_rate": 50.0,
      "interview_rate": 10.0,
      "offer_rate": 0.0,
      "placement_readiness_score": 35.8,
      "fill_risk_score": 84.1,
      "data_quality_score": 55.6,
      "expected_shortlist_days": 15.8,
      "placements": 0,
      "estimated_weekly_margin": 340.0,
      "recommendation": "Clean source data before promising a new shortlist",
      "recruiter_owner": "Enterprise desk",
      "priority_score": 85.4
    },
    {
      "role_id": "REQ003",
      "client_segment": "Insurance carrier",
      "role_family": "Cybersecurity Analyst",
      "city": "Cleveland",
      "work_structure": "Onsite",
      "priority": "High",
      "open_days": 51,
      "submit_rate": 40.0,
      "interview_rate": 20.0,
      "offer_rate": 0.0,
      "placement_readiness_score": 33.2,
      "fill_risk_score": 87.6,
      "data_quality_score": 55.6,
      "expected_shortlist_days": 16.8,
      "placements": 0,
      "estimated_weekly_margin": 290.0,
      "recommendation": "Clean source data before promising a new shortlist",
      "recruiter_owner": "Enterprise desk",
      "priority_score": 85.1
    },
    {
      "role_id": "REQ007",
      "client_segment": "Professional services firm",
      "role_family": "Finance Analyst",
      "city": "Columbus",
      "work_structure": "Remote",
      "priority": "High",
      "open_days": 42,
      "submit_rate": 53.5,
      "interview_rate": 34.2,
      "offer_rate": 7.7,
      "placement_readiness_score": 43.6,
      "fill_risk_score": 70.1,
      "data_quality_score": 50.4,
      "expected_shortlist_days": 13.9,
      "placements": 0,
      "estimated_weekly_margin": 1520.0,
      "recommendation": "Clean source data before promising a new shortlist",
      "recruiter_owner": "Enterprise desk",
      "priority_score": 82.9
    },
    {
      "role_id": "REQ005",
      "client_segment": "Energy utility",
      "role_family": "ERP Analyst",
      "city": "Louisville",
      "work_structure": "Onsite",
      "priority": "Critical",
      "open_days": 28,
      "submit_rate": 42.3,
      "interview_rate": 9.1,
      "offer_rate": 0.0,
      "placement_readiness_score": 22.7,
      "fill_risk_score": 87.4,
      "data_quality_score": 8.4,
      "expected_shortlist_days": 16.0,
      "placements": 0,
      "estimated_weekly_margin": 297.0,
      "recommendation": "Clean source data before promising a new shortlist",
      "recruiter_owner": "Specialty desk",
      "priority_score": 82.3
    },
    {
      "role_id": "REQ037",
      "client_segment": "Energy utility",
      "role_family": "Finance Analyst",
      "city": "Columbus",
      "work_structure": "Hybrid",
      "priority": "High",
      "open_days": 56,
      "submit_rate": 40.7,
      "interview_rate": 27.0,
      "offer_rate": 0.0,
      "placement_readiness_score": 37.9,
      "fill_risk_score": 72.8,
      "data_quality_score": 74.0,
      "expected_shortlist_days": 13.7,
      "placements": 0,
      "estimated_weekly_margin": 888.0,
      "recommendation": "Clean source data before promising a new shortlist",
      "recruiter_owner": "Specialty desk",
      "priority_score": 81.4
    }
  ],
  "qualityQueue": [
    {
      "check_id": "location_mismatch",
      "role_id": "REQ034",
      "check_name": "Location or work structure mismatch",
      "records_tested": 52,
      "issue_count": 10,
      "severity": "Fail",
      "owner": "North desk"
    },
    {
      "check_id": "missing_pay_rate",
      "role_id": "REQ005",
      "check_name": "Missing pay or bill rate",
      "records_tested": 50,
      "issue_count": 8,
      "severity": "Fail",
      "owner": "Specialty desk"
    },
    {
      "check_id": "skill_taxonomy_gap",
      "role_id": "REQ005",
      "check_name": "Skill taxonomy not standardized",
      "records_tested": 50,
      "issue_count": 8,
      "severity": "Fail",
      "owner": "Specialty desk"
    },
    {
      "check_id": "missing_pay_rate",
      "role_id": "REQ007",
      "check_name": "Missing pay or bill rate",
      "records_tested": 37,
      "issue_count": 8,
      "severity": "Fail",
      "owner": "Enterprise desk"
    },
    {
      "check_id": "missing_pay_rate",
      "role_id": "REQ039",
      "check_name": "Missing pay or bill rate",
      "records_tested": 48,
      "issue_count": 8,
      "severity": "Fail",
      "owner": "North desk"
    },
    {
      "check_id": "skill_taxonomy_gap",
      "role_id": "REQ009",
      "check_name": "Skill taxonomy not standardized",
      "records_tested": 49,
      "issue_count": 7,
      "severity": "Fail",
      "owner": "Central desk"
    },
    {
      "check_id": "missing_pay_rate",
      "role_id": "REQ026",
      "check_name": "Missing pay or bill rate",
      "records_tested": 42,
      "issue_count": 7,
      "severity": "Fail",
      "owner": "Enterprise desk"
    },
    {
      "check_id": "skill_taxonomy_gap",
      "role_id": "REQ030",
      "check_name": "Skill taxonomy not standardized",
      "records_tested": 50,
      "issue_count": 7,
      "severity": "Fail",
      "owner": "Central desk"
    },
    {
      "check_id": "location_mismatch",
      "role_id": "REQ032",
      "check_name": "Location or work structure mismatch",
      "records_tested": 38,
      "issue_count": 7,
      "severity": "Fail",
      "owner": "Central desk"
    },
    {
      "check_id": "skill_taxonomy_gap",
      "role_id": "REQ034",
      "check_name": "Skill taxonomy not standardized",
      "records_tested": 52,
      "issue_count": 7,
      "severity": "Fail",
      "owner": "North desk"
    },
    {
      "check_id": "skill_taxonomy_gap",
      "role_id": "REQ028",
      "check_name": "Skill taxonomy not standardized",
      "records_tested": 46,
      "issue_count": 6,
      "severity": "Fail",
      "owner": "Specialty desk"
    },
    {
      "check_id": "location_mismatch",
      "role_id": "REQ035",
      "check_name": "Location or work structure mismatch",
      "records_tested": 26,
      "issue_count": 6,
      "severity": "Fail",
      "owner": "Enterprise desk"
    }
  ],
  "actions": [
    {
      "action_id": "ACT001",
      "role_id": "REQ018",
      "action_type": "Data clean-up",
      "owner": "Analytics",
      "effort_hours": 4,
      "expected_shortlist_days": 18,
      "expected_margin_protected": 810.0,
      "status": "Ready for review"
    },
    {
      "action_id": "ACT002",
      "role_id": "REQ006",
      "action_type": "Data clean-up",
      "owner": "Analytics",
      "effort_hours": 4,
      "expected_shortlist_days": 16.5,
      "expected_margin_protected": 840.0,
      "status": "Ready for review"
    },
    {
      "action_id": "ACT003",
      "role_id": "REQ032",
      "action_type": "Data clean-up",
      "owner": "Analytics",
      "effort_hours": 4,
      "expected_shortlist_days": 18,
      "expected_margin_protected": 232.0,
      "status": "Ready for review"
    },
    {
      "action_id": "ACT004",
      "role_id": "REQ001",
      "action_type": "Data clean-up",
      "owner": "Analytics",
      "effort_hours": 4,
      "expected_shortlist_days": 14.1,
      "expected_margin_protected": 552.0,
      "status": "Ready for review"
    },
    {
      "action_id": "ACT005",
      "role_id": "REQ009",
      "action_type": "Data clean-up",
      "owner": "Analytics",
      "effort_hours": 4,
      "expected_shortlist_days": 16.1,
      "expected_margin_protected": 660.0,
      "status": "Ready for review"
    },
    {
      "action_id": "ACT006",
      "role_id": "REQ021",
      "action_type": "Data clean-up",
      "owner": "Analytics",
      "effort_hours": 4,
      "expected_shortlist_days": 16.2,
      "expected_margin_protected": 252.0,
      "status": "Ready for review"
    },
    {
      "action_id": "ACT007",
      "role_id": "REQ038",
      "action_type": "Executive review",
      "owner": "Enterprise desk",
      "effort_hours": 2,
      "expected_shortlist_days": 15.4,
      "expected_margin_protected": 986.0,
      "status": "Ready for review"
    },
    {
      "action_id": "ACT008",
      "role_id": "REQ042",
      "action_type": "Data clean-up",
      "owner": "Analytics",
      "effort_hours": 4,
      "expected_shortlist_days": 15.8,
      "expected_margin_protected": 340.0,
      "status": "Ready for review"
    },
    {
      "action_id": "ACT009",
      "role_id": "REQ003",
      "action_type": "Data clean-up",
      "owner": "Analytics",
      "effort_hours": 4,
      "expected_shortlist_days": 16.8,
      "expected_margin_protected": 290.0,
      "status": "Queued"
    },
    {
      "action_id": "ACT010",
      "role_id": "REQ007",
      "action_type": "Data clean-up",
      "owner": "Analytics",
      "effort_hours": 4,
      "expected_shortlist_days": 13.9,
      "expected_margin_protected": 1520.0,
      "status": "Queued"
    }
  ],
  "modelSummary": [
    {
      "metric": "Average placement readiness",
      "value": 36.4,
      "interpretation": "Higher means the role has enough clean funnel signal to move toward shortlist or placement."
    },
    {
      "metric": "Average fill risk",
      "value": 70.3,
      "interpretation": "Higher means aging, scarcity, poor conversion, or quality issues are likely to delay fill."
    },
    {
      "metric": "Quality checks requiring review",
      "value": 153,
      "interpretation": "Rows where source issues could distort reporting or recruiter action."
    },
    {
      "metric": "Top role priority score",
      "value": 110.0,
      "interpretation": "Composite decision score for this week's first operating review item."
    }
  ],
  "marketSignals": [
    {
      "skill": "SQL",
      "open_role_count": 42,
      "demand_index": 369.4,
      "available_supply_index": 71.0,
      "median_pay_rate": 57.0,
      "market_pressure": "High"
    },
    {
      "skill": "Excel",
      "open_role_count": 32,
      "demand_index": 352.2,
      "available_supply_index": 67.5,
      "median_pay_rate": 56.0,
      "market_pressure": "High"
    },
    {
      "skill": "Python",
      "open_role_count": 20,
      "demand_index": 218.2,
      "available_supply_index": 85.1,
      "median_pay_rate": 56.0,
      "market_pressure": "High"
    },
    {
      "skill": "Power BI",
      "open_role_count": 20,
      "demand_index": 160.1,
      "available_supply_index": 36.8,
      "median_pay_rate": 57.0,
      "market_pressure": "High"
    },
    {
      "skill": "Risk reporting",
      "open_role_count": 11,
      "demand_index": 131.4,
      "available_supply_index": 38.6,
      "median_pay_rate": 54.0,
      "market_pressure": "High"
    },
    {
      "skill": "Forecasting",
      "open_role_count": 11,
      "demand_index": 127.9,
      "available_supply_index": 48.0,
      "median_pay_rate": 59.0,
      "market_pressure": "High"
    },
    {
      "skill": "Cloud basics",
      "open_role_count": 7,
      "demand_index": 70.8,
      "available_supply_index": 90.2,
      "median_pay_rate": 63.0,
      "market_pressure": "Moderate"
    },
    {
      "skill": "Process mapping",
      "open_role_count": 6,
      "demand_index": 70.0,
      "available_supply_index": 67.4,
      "median_pay_rate": 56.0,
      "market_pressure": "High"
    }
  ],
  "brief": [
    {
      "brief_section": "Situation",
      "message": "Open analytical and technical roles have enough funnel activity to rank, but the riskiest roles combine aging, onsite constraints, and source-data issues."
    },
    {
      "brief_section": "Decision needed",
      "message": "Decide whether to clean records, reset sourcing, or calibrate with the client before increasing recruiter effort."
    },
    {
      "brief_section": "Recommended first move",
      "message": "Start with REQ018 in Industrial manufacturer: clean source data before promising a new shortlist."
    },
    {
      "brief_section": "Risk if ignored",
      "message": "Leadership may overreact to volume gaps while the root issue is conversion quality, stale stage data, or delayed client feedback."
    }
  ]
};
